# Generated by Django 6.0.4 on 2026-08-22 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionauditl1krt',
            name='score_ankle',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Ankle Mobility'),
        ),
        migrations.AddField(
            model_name='correctionauditl1krt',
            name='score_aslr',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor ASLR'),
        ),
        migrations.AddField(
            model_name='correctionauditl1krt',
            name='score_hip_rotation',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Hip Rotation Mobility'),
        ),
        migrations.AddField(
            model_name='correctionauditl1krt',
            name='score_lateral_pelvic',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Lateral Pelvic Stability'),
        ),
        migrations.AddField(
            model_name='correctionauditl1krt',
            name='score_lumbar_extension',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Lumbar Extension'),
        ),
        migrations.AddField(
            model_name='correctionauditl1krt',
            name='score_thoracic_rotation',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Thoracic Rotation'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1krt',
            name='balance_durasi_mata_terbuka',
            field=models.FloatField(blank=True, null=True, verbose_name='[Lama] Balance Mata Terbuka (detik)'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1krt',
            name='balance_durasi_mata_tertutup',
            field=models.FloatField(blank=True, null=True, verbose_name='[Lama] Balance Mata Tertutup (detik)'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1krt',
            name='core_hold_durasi_detik',
            field=models.FloatField(blank=True, null=True, verbose_name='[Lama] Pallof Press Hold (detik)'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1krt',
            name='hip_hinge_pass',
            field=models.BooleanField(default=False, verbose_name='[Lama] Hip Hinge Pattern Benar?'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1krt',
            name='recovery_waktu_detik',
            field=models.FloatField(blank=True, null=True, verbose_name='[Lama] Recovery Time (detik)'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1krt',
            name='skor_neural_ankle',
            field=models.IntegerField(choices=[(1, 'Cognitive'), (2, 'Associative'), (3, 'Autonomous')], default=1, verbose_name='[Lama] Skor Neural Ankle (skala 1-3)'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1krt',
            name='skor_neural_balance',
            field=models.IntegerField(choices=[(1, 'Cognitive'), (2, 'Associative'), (3, 'Autonomous')], default=1, verbose_name='[Lama] Skor Neural Balance'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1krt',
            name='skor_neural_core',
            field=models.IntegerField(choices=[(1, 'Cognitive'), (2, 'Associative'), (3, 'Autonomous')], default=1, verbose_name='[Lama] Skor Neural Core'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1krt',
            name='skor_neural_hamstring',
            field=models.IntegerField(choices=[(1, 'Cognitive'), (2, 'Associative'), (3, 'Autonomous')], default=1, verbose_name='[Lama] Skor Neural Hamstring (skala 1-3)'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1krt',
            name='skor_neural_hip_hinge',
            field=models.IntegerField(choices=[(1, 'Cognitive'), (2, 'Associative'), (3, 'Autonomous')], default=1, verbose_name='[Lama] Skor Neural Hip Hinge'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1krt',
            name='skor_neural_hip_rotasi',
            field=models.IntegerField(choices=[(1, 'Cognitive'), (2, 'Associative'), (3, 'Autonomous')], default=1, verbose_name='[Lama] Skor Neural Hip Rotasi (skala 1-3)'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1krt',
            name='skor_neural_recovery',
            field=models.IntegerField(choices=[(1, 'Cognitive'), (2, 'Associative'), (3, 'Autonomous')], default=1, verbose_name='[Lama] Skor Neural Recovery'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1krt',
            name='skor_neural_thoracic',
            field=models.IntegerField(choices=[(1, 'Cognitive'), (2, 'Associative'), (3, 'Autonomous')], default=1, verbose_name='[Lama] Skor Neural Thoracic (skala 1-3)'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1krt',
            name='total_skor',
            field=models.FloatField(default=0, verbose_name='Total Skor (0-10)'),
        ),
    ]
