# Generated by Django 6.0.4 on 2026-09-30 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketl2strength',
            old_name='grip_kanan_kg',
            new_name='broad_jump_m',
        ),
        migrations.RenameField(
            model_name='basketl2strength',
            old_name='score_grip',
            new_name='score_broad',
        ),
        migrations.RemoveField(
            model_name='basketl2strength',
            name='grip_kiri_kg',
        ),
    ]
