# Generated by Django 6.0.4 on 2026-10-09 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0002_rename_grip_kanan_kg_basketl2strength_broad_jump_m_and_more'),
        ('combat', '0023_alter_rekomendasiprogram_audit_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketl4specific',
            name='atlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l4_basketball', to='combat.atlet'),
        ),
        migrations.AlterField(
            model_name='basketl1correction',
            name='atlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l1_basketball', to='combat.atlet'),
        ),
        migrations.AlterField(
            model_name='basketl3power',
            name='atlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l3_basketball', to='combat.atlet'),
        ),
        migrations.AlterField(
            model_name='basketl2strength',
            name='atlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l2_basketball', to='combat.atlet'),
        ),
        migrations.CreateModel(
            name='ProfilBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi', models.CharField(blank=True, choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=5)),
                ('wingspan', models.FloatField(blank=True, null=True, verbose_name='Wingspan (cm)')),
                ('atlet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_basket', to='combat.atlet')),
            ],
            options={
                'verbose_name': 'Profil Basket',
                'verbose_name_plural': 'Profil Basket',
            },
        ),
        migrations.DeleteModel(
            name='AtletBasket',
        ),
        migrations.CreateModel(
            name='AtletBasket',
            fields=[
            ],
            options={
                'verbose_name': 'Atlet Basket',
                'verbose_name_plural': 'Atlet Basket',
                'ordering': ['nama_atlet'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('combat.atlet',),
        ),
    ]
