# Generated by Django 6.0.4 on 2026-10-10 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0003_atlet_proxy_combat'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketl3power',
            name='broad_jump_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basketl3power',
            name='score_broad',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='basketl3power',
            name='score_throw',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='basketl3power',
            name='throw_jarak_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basketl4specific',
            name='cod_detik',
            field=models.FloatField(blank=True, null=True, verbose_name='COD T-Test (detik)'),
        ),
        migrations.AddField(
            model_name='basketl4specific',
            name='lane_agility_detik',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basketl4specific',
            name='score_agility',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='basketl4specific',
            name='score_cod',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='basketl4specific',
            name='score_sprint',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='basketl4specific',
            name='sprint_30m_detik',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basketl4specific',
            name='sprint_court_detik',
            field=models.FloatField(blank=True, null=True, verbose_name='Sprint 3/4 Court (detik)'),
        ),
    ]
