path = r'combat\templates\combat\l1_correction.html'
with open(path, 'r', encoding='utf-8') as f:
    c = f.read()
start_tag = '<div class="rubrik-panel no-print" id="rubrikPanel"'
start_idx = c.find(start_tag)
pos=start_idx; depth=0; end_idx=-1; i=pos
while i < len(c):
    if c[i:i+4]=='<div': depth+=1; i+=4
    elif c[i:i+6]=='</div>':
        depth-=1
        if depth==0: end_idx=i+6; break
        i+=6
    else: i+=1
NEW="""<div class="rubrik-panel no-print" id="rubrikPanel" style="display:none">
<div class="rubrik-tabs"><span style="font-size:9px;color:#445566;margin-right:6px;">KATEGORI:</span><button class="rtab active" onclick="setRubrikKat(\'all\',this)">Semua</button><button class="rtab" onclick="setRubrikKat(\'elite\',this)">Elite</button><button class="rtab" onclick="setRubrikKat(\'youth\',this)">Youth</button><button class="rtab" onclick="setRubrikKat(\'junior\',this)">Junior</button></div>
<style>.rb-table{width:100%;border-collapse:collapse;font-size:10px;margin-bottom:0;}.rb-table th,.rb-table td{border:1px solid var(--border2);padding:7px 9px;vertical-align:top;line-height:1.5;}.rb-table ul{margin:2px 0;padding-left:14px;}.rb-th-aspek{background:#0a1e35;color:#00d2ff;font-weight:700;width:110px;}.rb-td-elite{background:rgba(0,255,136,0.05);color:#a0e4bc;}.rb-td-ready{background:rgba(56,189,248,0.05);color:#90cce8;}.rb-td-dev{background:rgba(255,179,0,0.05);color:#e8c870;}.rb-td-novice{background:rgba(255,107,107,0.05);color:#e89090;}.rb-section{font-size:10px;font-weight:900;color:#00d2ff;background:rgba(0,210,255,0.06);border-left:3px solid #00d2ff;padding:6px 12px;letter-spacing:1px;text-transform:uppercase;border-top:1px solid var(--border2);}</style>
<div class="rubrik-header" style="display:grid;grid-template-columns:110px 1fr 1fr 1fr 1fr;font-size:9px;font-weight:700;letter-spacing:1px;"><div style="background:#061020;color:#445566;">ASPEK</div><div style="background:#0d2d1a;color:#00ff88;text-align:center;">&#127942; VERY COMPETENT<br><span style="font-weight:400">(9-10)</span></div><div style="background:#0d2535;color:#38bdf8;text-align:center;">&#9989; COMPETENT<br><span style="font-weight:400">(7-8)</span></div><div style="background:#2a1e08;color:#ffb300;text-align:center;">&#128260; DEVELOPING<br><span style="font-weight:400">(5-6)</span></div><div style="background:#2a0d0d;color:#ff6b6b;text-align:center;">&#9888; NOVICE<br><span style="font-weight:400">(1-4)</span></div></div>
<div class="rb-section">Pilar 1 &#8212; Rotation</div>
<table class="rb-table"><tbody><tr><td class="rb-th-aspek">Seated Rotation Test<br><small style="color:var(--text3)">Kiri &amp; Kanan</small></td><td class="rb-td-elite"><ul><li>E: &gt;50&#176;</li><li>Y: &gt;45&#176;</li><li>J: &gt;40&#176;</li></ul></td><td class="rb-td-ready"><ul><li>E: 40-50&#176;</li><li>Y: 35-45&#176;</li><li>J: 30-40&#176;</li></ul></td><td class="rb-td-dev"><ul><li>E: 30-40&#176;</li><li>Y: 25-35&#176;</li><li>J: 20-30&#176;</li></ul></td><td class="rb-td-novice"><ul><li>E: &lt;30&#176;</li><li>Y: &lt;25&#176;</li><li>J: &lt;20&#176;</li></ul></td></tr><tr><td class="rb-th-aspek">Simetri L-R</td><td class="rb-td-elite"><ul><li>Selisih &#8804;3&#176;</li><li>Gerakan fluid</li></ul></td><td class="rb-td-ready"><ul><li>Selisih 4-8&#176;</li></ul></td><td class="rb-td-dev"><ul><li>Selisih 9-15&#176;</li></ul></td><td class="rb-td-novice"><ul><li>Selisih &gt;15&#176; / nyeri</li></ul></td></tr></tbody></table>
<div class="rb-section">Pilar 2 &#8212; Extension</div>
<table class="rb-table"><tbody><tr><td class="rb-th-aspek">Lumbar Extension Test</td><td class="rb-td-elite"><ul><li>E: &gt;25 cm</li><li>Y: &gt;20 cm</li><li>J: &gt;15 cm</li></ul></td><td class="rb-td-ready"><ul><li>E: 15-25 cm</li><li>Y: 12-20 cm</li><li>J: 10-15 cm</li></ul></td><td class="rb-td-dev"><ul><li>E: 10-15 cm</li><li>Y: 8-12 cm</li><li>J: 5-10 cm</li></ul></td><td class="rb-td-novice"><ul><li>E: &lt;10 cm</li><li>Y: &lt;8 cm</li><li>J: &lt;5 cm</li></ul></td></tr></tbody></table>
<div class="rb-section">Pilar 3 &#8212; Stability</div>
<table class="rb-table"><tbody><tr><td class="rb-th-aspek">Single Leg Balance<br><small style="color:var(--text3)">Detik</small></td><td class="rb-td-elite"><ul><li>E: &gt;45 dtk</li><li>Y: &gt;35 dtk</li><li>J: &gt;30 dtk</li></ul></td><td class="rb-td-ready"><ul><li>E: 30-45 dtk</li><li>Y: 25-35 dtk</li><li>J: 20-30 dtk</li></ul></td><td class="rb-td-dev"><ul><li>E: 15-30 dtk</li><li>Y: 12-25 dtk</li><li>J: 10-20 dtk</li></ul></td><td class="rb-td-novice"><ul><li>E: &lt;15 dtk</li><li>Y: &lt;12 dtk</li><li>J: &lt;10 dtk</li></ul></td></tr><tr><td class="rb-th-aspek">Core Plank Hold</td><td class="rb-td-elite"><ul><li>&#8805;60 dtk stabil</li><li>Panggul netral</li></ul></td><td class="rb-td-ready"><ul><li>45-59 dtk</li></ul></td><td class="rb-td-dev"><ul><li>25-44 dtk</li></ul></td><td class="rb-td-novice"><ul><li>&lt;25 dtk</li></ul></td></tr></tbody></table>
<div class="rb-section">Pilar 4 &#8212; Posture</div>
<table class="rb-table"><tbody><tr><td class="rb-th-aspek">Lateral Alignment</td><td class="rb-td-elite"><ul><li>Satu garis sempurna</li><li>Kurva spinal normal</li></ul></td><td class="rb-td-ready"><ul><li>Deviasi 1 segmen</li></ul></td><td class="rb-td-dev"><ul><li>Deviasi 2 segmen</li><li>Forward head</li></ul></td><td class="rb-td-novice"><ul><li>Deviasi &#8805;3 segmen</li></ul></td></tr><tr><td class="rb-th-aspek">Boxing Guard</td><td class="rb-td-elite"><ul><li>Chin tucked, elbows in</li><li>Weight 60-40</li></ul></td><td class="rb-td-ready"><ul><li>1-2 koreksi minor</li></ul></td><td class="rb-td-dev"><ul><li>Guard terbuka</li></ul></td><td class="rb-td-novice"><ul><li>Guard sangat buruk</li></ul></td></tr></tbody></table>
<div class="rb-section">Pilar 5 &#8212; Breathing</div>
<table class="rb-table"><tbody><tr><td class="rb-th-aspek">Pola Istirahat</td><td class="rb-td-elite"><ul><li>Diafragma dominan</li><li>12-16 napas/mnt</li></ul></td><td class="rb-td-ready"><ul><li>16-18 napas/mnt</li></ul></td><td class="rb-td-dev"><ul><li>18-22 napas/mnt</li></ul></td><td class="rb-td-novice"><ul><li>&gt;22 napas/mnt</li></ul></td></tr><tr><td class="rb-th-aspek">Saat Tekanan</td><td class="rb-td-elite"><ul><li>Napas terkontrol</li></ul></td><td class="rb-td-ready"><ul><li>Tahan &lt;5 dtk</li></ul></td><td class="rb-td-dev"><ul><li>Valsava tidak tepat</li></ul></td><td class="rb-td-novice"><ul><li>Tidak bisa napas sambil gerak</li></ul></td></tr></tbody></table>
<div class="rb-section">Pilar 6 &#8212; Ankle Mobility</div>
<table class="rb-table"><tbody><tr><td class="rb-th-aspek">Knee-to-Wall Test<br><small style="color:var(--text3)">(cm)</small></td><td class="rb-td-elite"><ul><li>E: &#8805;12 cm</li><li>Y: &#8805;10 cm</li><li>J: &#8805;9 cm</li></ul></td><td class="rb-td-ready"><ul><li>E: 9-11 cm</li><li>Y: 7-9 cm</li><li>J: 6-8 cm</li></ul></td><td class="rb-td-dev"><ul><li>E: 6-8 cm</li><li>Y: 5-6 cm</li><li>J: 4-5 cm</li></ul></td><td class="rb-td-novice"><ul><li>E: &lt;6 cm</li><li>Y: &lt;5 cm</li><li>J: &lt;4 cm</li></ul></td></tr></tbody></table>
<div style="padding:8px 12px;font-size:9px;color:var(--text3);border-top:1px solid var(--border2);"><strong style="color:var(--cyan);">Ket:</strong> E=Elite | Y=Youth | J=Junior | Skor 9-10: Very Competent | 7-8: Competent | 5-6: Developing | 1-4: Novice</div>
</div>"""
c = c[:start_idx] + NEW + c[end_idx:]
with open(path, 'w', encoding='utf-8') as f:
    f.write(c)
print('DONE')
