# Generated by Django 6.0.4 on 2026-07-14 23:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combat', '0008_alter_correctionauditl1_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionAuditL1TKD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atlet_name', models.CharField(blank=True, max_length=150, verbose_name='Nama Atlet (form)')),
                ('kategori_usia', models.CharField(choices=[('ELITE', 'Elite'), ('YOUTH', 'Youth'), ('JUNIOR', 'Junior'), ('SENIOR', 'Senior')], default='ELITE', max_length=20)),
                ('gender', models.CharField(choices=[('Putra', 'Putra'), ('Putri', 'Putri')], default='Putra', max_length=10)),
                ('kelas_berat', models.FloatField(blank=True, null=True, verbose_name='Berat Badan (kg)')),
                ('hip_rotasi_internal_kanan', models.FloatField(blank=True, null=True, verbose_name='Hip Internal Rotation Kanan (derajat)')),
                ('hip_rotasi_internal_kiri', models.FloatField(blank=True, null=True, verbose_name='Hip Internal Rotation Kiri (derajat)')),
                ('hip_rotasi_eksternal_kanan', models.FloatField(blank=True, null=True, verbose_name='Hip External Rotation Kanan (derajat)')),
                ('hip_rotasi_eksternal_kiri', models.FloatField(blank=True, null=True, verbose_name='Hip External Rotation Kiri (derajat)')),
                ('skor_neural_hip_rotasi', models.IntegerField(choices=[(1, 'Cognitive'), (2, 'Associative'), (3, 'Autonomous')], default=1)),
                ('balance_durasi_mata_terbuka', models.FloatField(blank=True, null=True, verbose_name='Balance Mata Terbuka (detik)')),
                ('balance_durasi_mata_tertutup', models.FloatField(blank=True, null=True, verbose_name='Balance Mata Tertutup (detik)')),
                ('skor_neural_balance', models.IntegerField(choices=[(1, 'Cognitive'), (2, 'Associative'), (3, 'Autonomous')], default=1)),
                ('ankle_dorsifleksi_kanan_cm', models.FloatField(blank=True, null=True, verbose_name='Ankle Dorsiflexion Kanan (cm)')),
                ('ankle_dorsifleksi_kiri_cm', models.FloatField(blank=True, null=True, verbose_name='Ankle Dorsiflexion Kiri (cm)')),
                ('skor_neural_ankle', models.IntegerField(choices=[(1, 'Cognitive'), (2, 'Associative'), (3, 'Autonomous')], default=1)),
                ('thoracic_rotasi_kanan', models.FloatField(blank=True, null=True, verbose_name='Thoracic Rotation Kanan (derajat)')),
                ('thoracic_rotasi_kiri', models.FloatField(blank=True, null=True, verbose_name='Thoracic Rotation Kiri (derajat)')),
                ('skor_neural_thoracic', models.IntegerField(choices=[(1, 'Cognitive'), (2, 'Associative'), (3, 'Autonomous')], default=1)),
                ('asl_raise_kanan_derajat', models.FloatField(blank=True, null=True, verbose_name='Active Straight Leg Raise Kanan (derajat)')),
                ('asl_raise_kiri_derajat', models.FloatField(blank=True, null=True, verbose_name='Active Straight Leg Raise Kiri (derajat)')),
                ('skor_neural_hamstring', models.IntegerField(choices=[(1, 'Cognitive'), (2, 'Associative'), (3, 'Autonomous')], default=1)),
                ('hip_hinge_pass', models.BooleanField(default=False, verbose_name='Hip Hinge Pattern Benar?')),
                ('skor_neural_hip_hinge', models.IntegerField(choices=[(1, 'Cognitive'), (2, 'Associative'), (3, 'Autonomous')], default=1)),
                ('core_hold_durasi_detik', models.FloatField(blank=True, null=True, verbose_name='Pallof Press Hold (detik)')),
                ('skor_neural_core', models.IntegerField(choices=[(1, 'Cognitive'), (2, 'Associative'), (3, 'Autonomous')], default=1)),
                ('recovery_waktu_detik', models.FloatField(blank=True, null=True, verbose_name='Recovery Time (detik)')),
                ('skor_neural_recovery', models.IntegerField(choices=[(1, 'Cognitive'), (2, 'Associative'), (3, 'Autonomous')], default=1)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('total_skor', models.FloatField(default=0, verbose_name='Total Skor Neural (0-10)')),
                ('predikat', models.CharField(choices=[('ELITE', 'Elite'), ('READY', 'Ready'), ('DEVELOPING', 'Developing'), ('NOVICE', 'Novice')], default='NOVICE', max_length=20)),
                ('layak_naik', models.BooleanField(default=False, verbose_name='Layak Naik ke L2?')),
                ('alasan_tidak_layak', models.CharField(blank=True, max_length=255)),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan Coach')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, default='Coach Fanny', max_length=100)),
                ('atlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_l1_tkd', to='combat.atlet', verbose_name='Atlet')),
            ],
            options={
                'verbose_name': 'L1 Correction Taekwondo',
                'verbose_name_plural': 'L1 Correction Taekwondo',
                'db_table': 'taekwondo_correction_audit_l1',
                'ordering': ['-timestamp'],
            },
        ),
    ]
