# Generated by Django 6.0.4 on 2026-08-14 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taekwondo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctionauditl1tkd',
            name='skor_neural_ankle',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='correctionauditl1tkd',
            name='skor_neural_balance',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='correctionauditl1tkd',
            name='skor_neural_core',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='correctionauditl1tkd',
            name='skor_neural_hamstring',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='correctionauditl1tkd',
            name='skor_neural_hip_hinge',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='correctionauditl1tkd',
            name='skor_neural_hip_rotasi',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='correctionauditl1tkd',
            name='skor_neural_recovery',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='correctionauditl1tkd',
            name='skor_neural_thoracic',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='correctionauditl1tkd',
            name='total_skor',
            field=models.FloatField(default=0, verbose_name='Total Skor (0-10)'),
        ),
    ]
