# Generated by Django 6.0.4 on 2026-08-23 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taekwondo', '0002_alter_correctionauditl1tkd_skor_neural_ankle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correctionauditl1tkd',
            old_name='hip_rotasi_eksternal_kanan',
            new_name='hip_er_kanan_derajat',
        ),
        migrations.RenameField(
            model_name='correctionauditl1tkd',
            old_name='hip_rotasi_eksternal_kiri',
            new_name='hip_er_kiri_derajat',
        ),
        migrations.RenameField(
            model_name='correctionauditl1tkd',
            old_name='hip_rotasi_internal_kanan',
            new_name='hip_ir_kanan_derajat',
        ),
        migrations.RenameField(
            model_name='correctionauditl1tkd',
            old_name='hip_rotasi_internal_kiri',
            new_name='hip_ir_kiri_derajat',
        ),
        migrations.RenameField(
            model_name='correctionauditl1tkd',
            old_name='skor_neural_ankle',
            new_name='skor_ankle',
        ),
        migrations.RenameField(
            model_name='correctionauditl1tkd',
            old_name='skor_neural_balance',
            new_name='skor_balance',
        ),
        migrations.RenameField(
            model_name='correctionauditl1tkd',
            old_name='skor_neural_core',
            new_name='skor_hip_er',
        ),
        migrations.RenameField(
            model_name='correctionauditl1tkd',
            old_name='skor_neural_hip_hinge',
            new_name='skor_hip_ir',
        ),
        migrations.RenameField(
            model_name='correctionauditl1tkd',
            old_name='skor_neural_hamstring',
            new_name='skor_lumbar',
        ),
        migrations.RenameField(
            model_name='correctionauditl1tkd',
            old_name='skor_neural_hip_rotasi',
            new_name='skor_napas',
        ),
        migrations.RenameField(
            model_name='correctionauditl1tkd',
            old_name='skor_neural_recovery',
            new_name='skor_postur',
        ),
        migrations.RenameField(
            model_name='correctionauditl1tkd',
            old_name='skor_neural_thoracic',
            new_name='skor_trunk_rotation',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1tkd',
            name='ankle_dorsifleksi_kanan_cm',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1tkd',
            name='ankle_dorsifleksi_kiri_cm',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1tkd',
            name='asl_raise_kanan_derajat',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1tkd',
            name='asl_raise_kiri_derajat',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1tkd',
            name='balance_durasi_mata_terbuka',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1tkd',
            name='balance_durasi_mata_tertutup',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1tkd',
            name='core_hold_durasi_detik',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1tkd',
            name='hip_hinge_pass',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1tkd',
            name='recovery_waktu_detik',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1tkd',
            name='thoracic_rotasi_kanan',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1tkd',
            name='thoracic_rotasi_kiri',
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='lumbar_status',
            field=models.CharField(choices=[('NYERI', 'Nyeri (safety override — skor 0, rujuk)'), ('TERBATAS', 'Tidak nyeri, tapi kaku/terbatas/ada kompensasi bahu'), ('MULUS', 'Bebas nyeri, gerakan mulus, panggul tetap menempel')], default='MULUS', max_length=20),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='napas_status',
            field=models.CharField(choices=[('DADA_DOMINAN', 'Gerak dada atas tampak dominan'), ('CAMPURAN', 'Pola campuran'), ('ABDOMINAL_DOMINAN', 'Ekspansi abdominal/lateral lower-rib tampak dominan')], default='ABDOMINAL_DOMINAN', max_length=20),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='panjang_tungkai_kanan_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Panjang Tungkai Kanan (ASIS-maleolus, cm)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='panjang_tungkai_kiri_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Panjang Tungkai Kiri (ASIS-maleolus, cm)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='postur_status',
            field=models.CharField(choices=[('DEVIASI_JELAS', 'Deviasi jelas'), ('DEVIASI_RINGAN', 'Deviasi ringan'), ('TANPA_DEVIASI', 'Tanpa deviasi jelas')], default='TANPA_DEVIASI', max_length=20),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='skor_ybalance',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='slst_kanan_detik',
            field=models.FloatField(blank=True, null=True, verbose_name='SLST Kaki Kanan Tumpu (detik, terbaik dari 2 trial)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='slst_kiri_detik',
            field=models.FloatField(blank=True, null=True, verbose_name='SLST Kaki Kiri Tumpu (detik, terbaik dari 2 trial)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='status_keputusan',
            field=models.CharField(choices=[('HIJAU', 'Hijau — Lanjut program'), ('KUNING', 'Kuning — Korektif & retest'), ('MERAH', 'Merah — Dihentikan & dirujuk')], default='HIJAU', max_length=10, verbose_name='Kategori Keputusan HPCS (Hijau/Kuning/Merah)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='trunk_rotasi_kanan_derajat',
            field=models.FloatField(blank=True, null=True, verbose_name='Trunk Rotation Kanan (derajat)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='trunk_rotasi_kiri_derajat',
            field=models.FloatField(blank=True, null=True, verbose_name='Trunk Rotation Kiri (derajat)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='wblt_kanan_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='WBLT Kanan (cm)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='wblt_kiri_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='WBLT Kiri (cm)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='ybt_ant_kanan_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='YBT Anterior — Tumpu Kanan (cm)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='ybt_ant_kiri_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='YBT Anterior — Tumpu Kiri (cm)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='ybt_pl_kanan_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='YBT Posterolateral — Tumpu Kanan (cm)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='ybt_pl_kiri_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='YBT Posterolateral — Tumpu Kiri (cm)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='ybt_pm_kanan_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='YBT Posteromedial — Tumpu Kanan (cm)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1tkd',
            name='ybt_pm_kiri_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='YBT Posteromedial — Tumpu Kiri (cm)'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1tkd',
            name='total_skor',
            field=models.FloatField(default=0, verbose_name='Total Skor (0-10, rata-rata 8 pilar numerik)'),
        ),
    ]
