# Generated by Django 6.0.4 on 2026-08-30 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combat', '0016_seed_cabor_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_program', models.CharField(help_text="mis. 'Persiapan PON 2028'", max_length=150)),
                ('event_target', models.CharField(choices=[('kejurda', 'Kejuaraan Daerah (Kejurda)'), ('kejurnas', 'Kejuaraan Nasional (Kejurnas)'), ('pon', 'PON'), ('sea_games', 'SEA Games'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('nama_event', models.CharField(blank=True, help_text="Detail nama event, mis. 'PON XXII Aceh-Sumut'", max_length=150)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_target', models.DateField(help_text='Tanggal event kompetisi yang dituju')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AKTIF', 'Aktif Berjalan'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], default='DRAFT', max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('atlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macro_programs', to='combat.atlet')),
            ],
            options={
                'verbose_name': 'Makrosiklus (Program Jangka Panjang)',
                'verbose_name_plural': 'Makrosiklus (Program Jangka Panjang)',
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='MesoCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_fase', models.CharField(choices=[('GPP', 'General Physical Preparation'), ('SPP', 'Specific Physical Preparation'), ('PRE_COMP', 'Pre-Competition'), ('COMP', 'Competition'), ('TRANSISI', 'Transisi / Recovery')], max_length=20)),
                ('urutan', models.PositiveIntegerField(default=1, help_text='Urutan fase ini dalam macro program, mis. 1, 2, 3')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('fokus_l1_persen', models.PositiveIntegerField(default=25, help_text='Porsi fokus Koreksi/Mobility (L1)')),
                ('fokus_l2_persen', models.PositiveIntegerField(default=25, help_text='Porsi fokus Strength (L2)')),
                ('fokus_l3_persen', models.PositiveIntegerField(default=25, help_text='Porsi fokus Power (L3)')),
                ('fokus_l4_persen', models.PositiveIntegerField(default=25, help_text='Porsi fokus Speed/Agility (L4)')),
                ('volume_target', models.PositiveIntegerField(default=5, help_text='Skala 1-10')),
                ('intensitas_target', models.PositiveIntegerField(default=5, help_text='Skala 1-10')),
                ('catatan', models.TextField(blank=True)),
                ('macro_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meso_cycles', to='periodization.macroprogram')),
            ],
            options={
                'verbose_name': 'Mesosiklus (Fase 4-6 Minggu)',
                'verbose_name_plural': 'Mesosiklus (Fase 4-6 Minggu)',
                'ordering': ['macro_program', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='MicroCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minggu_ke', models.PositiveIntegerField(help_text='Minggu ke berapa dalam mesocycle ini, mis. 1, 2, 3')),
                ('tanggal_mulai', models.DateField(help_text='Tanggal Senin di minggu ini')),
                ('catatan', models.TextField(blank=True)),
                ('meso_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_cycles', to='periodization.mesocycle')),
            ],
            options={
                'verbose_name': 'Mikrosiklus (Minggu Latihan)',
                'verbose_name_plural': 'Mikrosiklus (Minggu Latihan)',
                'ordering': ['meso_cycle', 'minggu_ke'],
                'unique_together': {('meso_cycle', 'minggu_ke')},
            },
        ),
    ]
