# Generated by Django 6.0.4 on 2026-09-03 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesocycle',
            name='objektif_fisik',
            field=models.TextField(blank=True, help_text="mis. 'Bangun basis kekuatan umum & daya tahan aerobik'"),
        ),
        migrations.CreateModel(
            name='KompetisiTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kompetisi', models.CharField(help_text="mis. 'Kejurda Sumut 2027'", max_length=150)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField(blank=True, help_text='Kosongkan kalau kompetisi cuma 1 hari', null=True)),
                ('level', models.CharField(choices=[('domestik', 'Domestik'), ('internasional', 'Internasional'), ('kualifikasi', 'Kualifikasi')], default='domestik', max_length=20)),
                ('status', models.CharField(choices=[('TARGET_UTAMA', 'Target Utama'), ('OPSIONAL', 'Opsional'), ('PERTIMBANGAN_PELATIH', 'Berdasarkan Pertimbangan Pelatih')], default='OPSIONAL', max_length=25)),
                ('catatan', models.TextField(blank=True)),
                ('macro_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kompetisi_list', to='periodization.macroprogram')),
            ],
            options={
                'verbose_name': 'Target Kompetisi',
                'verbose_name_plural': 'Kalender Kompetisi',
                'ordering': ['tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='SesiLatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari_ke', models.PositiveSmallIntegerField(help_text='1=Senin ... 7=Minggu')),
                ('nama_sesi', models.CharField(help_text="mis. 'Strength AM', 'Speed & Agility'", max_length=150)),
                ('pilar_fokus', models.CharField(choices=[('L1', 'L1 - Correction / Mobility'), ('L2', 'L2 - Strength'), ('L3', 'L3 - Power'), ('L4', 'L4 - Speed & Agility'), ('TEKNIK', 'Teknik / Skill'), ('RECOVERY', 'Recovery / Regenerasi'), ('REST', 'Istirahat Penuh'), ('KOMPETISI', 'Kompetisi / Try-Out')], default='REST', max_length=10)),
                ('durasi_menit', models.PositiveIntegerField(default=0, help_text='Total durasi sesi (menit)')),
                ('intensitas', models.PositiveIntegerField(default=5, help_text='Skala 1-10')),
                ('catatan', models.TextField(blank=True)),
                ('micro_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_latihan', to='periodization.microcycle')),
            ],
            options={
                'verbose_name': 'Sesi Latihan Harian',
                'verbose_name_plural': 'Sesi Latihan Harian',
                'ordering': ['micro_cycle', 'hari_ke'],
            },
        ),
        migrations.CreateModel(
            name='LatihanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveIntegerField(default=1)),
                ('nama_latihan', models.CharField(help_text="mis. 'Barbell Back Squat'", max_length=150)),
                ('jumlah_set', models.PositiveIntegerField(default=1)),
                ('jumlah_rep', models.CharField(help_text="mis. '8', '8-12', 'AMRAP'", max_length=30)),
                ('beban_intensitas', models.CharField(blank=True, help_text="mis. '70% 1RM', 'RPE 7', '20kg'", max_length=50)),
                ('durasi_istirahat_detik', models.PositiveIntegerField(default=60, help_text='Istirahat antar set (detik)')),
                ('catatan', models.TextField(blank=True)),
                ('sesi_latihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latihan_items', to='periodization.sesilatihan')),
            ],
            options={
                'verbose_name': 'Item Latihan (Exercise)',
                'verbose_name_plural': 'Item Latihan (Exercise)',
                'ordering': ['sesi_latihan', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='TargetPerforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilar', models.CharField(choices=[('L1', 'L1 - Correction / Mobility'), ('L2', 'L2 - Strength'), ('L3', 'L3 - Power'), ('L4', 'L4 - Speed & Agility'), ('CUSTOM', 'Target Kustom Pelatih')], default='CUSTOM', max_length=10)),
                ('nama_test', models.CharField(help_text="mis. '20m Sprint', 'Vertical Jump', atau nama test custom pelatih", max_length=150)),
                ('nilai_target', models.FloatField(help_text='Nilai target yang mau dicapai')),
                ('satuan', models.CharField(help_text="mis. 'detik', 'cm', 'kg', 'reps'", max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('meso_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_performa', to='periodization.mesocycle')),
            ],
            options={
                'verbose_name': 'Target Performa',
                'verbose_name_plural': 'Target Performa per Fase',
                'ordering': ['meso_cycle', 'pilar', 'nama_test'],
            },
        ),
    ]
