# Generated by Django 6.0.4 on 2026-09-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodization', '0002_mesocycle_objektif_fisik_kompetisitarget_sesilatihan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latihanitem',
            name='kategori',
            field=models.CharField(choices=[('PEMANASAN', 'Pemanasan'), ('INTI', 'Latihan Inti'), ('PENDINGINAN', 'Pendinginan')], default='INTI', max_length=15),
        ),
        migrations.AddField(
            model_name='latihanitem',
            name='link_video',
            field=models.URLField(blank=True, help_text='Link video contoh gerakan (opsional)'),
        ),
        migrations.AddField(
            model_name='latihanitem',
            name='waktu',
            field=models.CharField(blank=True, help_text="mis. '30 detik', '20+' -- buat latihan berbasis durasi/jarak, terpisah dari jumlah_rep", max_length=30),
        ),
        migrations.AlterField(
            model_name='latihanitem',
            name='jumlah_rep',
            field=models.CharField(blank=True, help_text="mis. '8', '8-12', 'AMRAP'", max_length=30),
        ),
    ]
