# Generated by Django 6.0.4 on 2026-09-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodization', '0003_latihanitem_kategori_latihanitem_link_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesocycle',
            name='objektif_mental',
            field=models.TextField(blank=True, help_text='Objektif mental/psikologis fase ini'),
        ),
        migrations.AddField(
            model_name='mesocycle',
            name='objektif_taktik',
            field=models.TextField(blank=True, help_text='Objektif taktik fase ini'),
        ),
        migrations.AddField(
            model_name='mesocycle',
            name='objektif_teknik',
            field=models.TextField(blank=True, help_text='Objektif teknik/skill fase ini'),
        ),
    ]
