# Generated by Django 6.0.4 on 2026-09-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodization', '0004_mesocycle_objektif_mental_mesocycle_objektif_taktik_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesilatihan',
            options={'ordering': ['micro_cycle', 'hari_ke', 'waktu_sesi'], 'verbose_name': 'Sesi Latihan Harian', 'verbose_name_plural': 'Sesi Latihan Harian'},
        ),
        migrations.AddField(
            model_name='sesilatihan',
            name='waktu_sesi',
            field=models.CharField(choices=[('PAGI', 'Pagi'), ('SIANG', 'Siang'), ('SORE', 'Sore'), ('MALAM', 'Malam')], default='SORE', help_text='Buat bedain kalau 1 hari ada lebih dari 1 sesi', max_length=10),
        ),
    ]
