# Generated by Django 6.0.4 on 2026-08-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaythai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correctionauditl1mt',
            old_name='hip_rotasi_eksternal_kanan',
            new_name='hip_er_kanan',
        ),
        migrations.RenameField(
            model_name='correctionauditl1mt',
            old_name='hip_rotasi_eksternal_kiri',
            new_name='hip_er_kiri',
        ),
        migrations.RenameField(
            model_name='correctionauditl1mt',
            old_name='hip_rotasi_internal_kanan',
            new_name='hip_ir_kanan',
        ),
        migrations.RenameField(
            model_name='correctionauditl1mt',
            old_name='hip_rotasi_internal_kiri',
            new_name='hip_ir_kiri',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1mt',
            name='ankle_dorsifleksi_kanan_cm',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1mt',
            name='ankle_dorsifleksi_kiri_cm',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1mt',
            name='balance_durasi_mata_terbuka',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1mt',
            name='balance_durasi_mata_tertutup',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1mt',
            name='core_hold_durasi_detik',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1mt',
            name='hip_hinge_pass',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1mt',
            name='recovery_waktu_detik',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1mt',
            name='shoulder_fleksi_kanan',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1mt',
            name='shoulder_fleksi_kiri',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1mt',
            name='skor_neural_ankle',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1mt',
            name='skor_neural_balance',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1mt',
            name='skor_neural_core',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1mt',
            name='skor_neural_hip_hinge',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1mt',
            name='skor_neural_hip_rotasi',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1mt',
            name='skor_neural_recovery',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1mt',
            name='skor_neural_shoulder',
        ),
        migrations.RemoveField(
            model_name='correctionauditl1mt',
            name='skor_neural_thoracic',
        ),
        migrations.AddField(
            model_name='correctionauditl1mt',
            name='aslr_kanan',
            field=models.FloatField(blank=True, null=True, verbose_name='ASLR Kanan (derajat)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1mt',
            name='aslr_kiri',
            field=models.FloatField(blank=True, null=True, verbose_name='ASLR Kiri (derajat)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1mt',
            name='lumbar_kualitas',
            field=models.CharField(choices=[('MULUS', 'Ekstensi mulus, tanpa kompensasi'), ('KOMPENSASI', 'Ada kompensasi bahu/panggul terangkat'), ('TERBATAS', 'ROM sangat terbatas')], default='MULUS', max_length=20, verbose_name='Kualitas Ekstensi Thoracolumbar'),
        ),
        migrations.AddField(
            model_name='correctionauditl1mt',
            name='lumbar_nyeri',
            field=models.BooleanField(default=False, verbose_name='Nyeri saat Ekstensi? (Clearing Gate Gagal)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1mt',
            name='pelvic_stability_kanan',
            field=models.CharField(choices=[('STABIL', 'Alignment lurus, panggul stabil (tanpa valgus)'), ('RINGAN', 'Lutut bergoyang ringan / kompensasi minim'), ('VALGUS', 'Knee valgus parah / panggul anjlok (Trendelenburg sign)')], default='STABIL', max_length=20, verbose_name='Pelvic Stability Kanan'),
        ),
        migrations.AddField(
            model_name='correctionauditl1mt',
            name='pelvic_stability_kiri',
            field=models.CharField(choices=[('STABIL', 'Alignment lurus, panggul stabil (tanpa valgus)'), ('RINGAN', 'Lutut bergoyang ringan / kompensasi minim'), ('VALGUS', 'Knee valgus parah / panggul anjlok (Trendelenburg sign)')], default='STABIL', max_length=20, verbose_name='Pelvic Stability Kiri'),
        ),
        migrations.AddField(
            model_name='correctionauditl1mt',
            name='skor_ankle_mobility',
            field=models.IntegerField(default=5, verbose_name='Skor Ankle Mobility (1-10)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1mt',
            name='skor_aslr',
            field=models.IntegerField(default=5, verbose_name='Skor ASLR (1-10)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1mt',
            name='skor_hip_rotation',
            field=models.IntegerField(default=5, verbose_name='Skor Hip Rotation IR/ER (1-10)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1mt',
            name='skor_lumbar_extension',
            field=models.IntegerField(default=5, verbose_name='Skor Lumbar Extension (1-10)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1mt',
            name='skor_pelvic_stability',
            field=models.IntegerField(default=5, verbose_name='Skor Lateral Pelvic Stability (1-10)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1mt',
            name='skor_thoracic_rotation',
            field=models.IntegerField(default=5, verbose_name='Skor Thoracic Rotation (1-10)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1mt',
            name='wblt_jarak_kanan_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='WBLT Kanan (cm)'),
        ),
        migrations.AddField(
            model_name='correctionauditl1mt',
            name='wblt_jarak_kiri_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='WBLT Kiri (cm)'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1mt',
            name='total_skor',
            field=models.FloatField(default=0, verbose_name='Total Skor L1 (0-10)'),
        ),
    ]
