# Generated by Django 6.0.4 on 2026-09-14 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combat', '0017_alter_atlet_cabang_alter_profilpelatih_cabang'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionAuditL1SB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_usia', models.CharField(choices=[('YOUTH', 'Youth (6-12)'), ('JUNIOR', 'Junior (13-17)'), ('SENIOR', 'Senior (18-35)'), ('ELITE', 'Elite')], max_length=10)),
                ('gender', models.CharField(choices=[('PUTRA', 'Putra'), ('PUTRI', 'Putri')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ankle_kiri_cm', models.FloatField(blank=True, null=True)),
                ('ankle_kanan_cm', models.FloatField(blank=True, null=True)),
                ('score_ankle', models.FloatField(blank=True, null=True)),
                ('aslr_kiri_derajat', models.FloatField(blank=True, null=True)),
                ('aslr_kanan_derajat', models.FloatField(blank=True, null=True)),
                ('score_aslr', models.FloatField(blank=True, null=True)),
                ('hip_kiri_derajat', models.FloatField(blank=True, null=True)),
                ('hip_kanan_derajat', models.FloatField(blank=True, null=True)),
                ('score_hip', models.FloatField(blank=True, null=True)),
                ('kena_penalti_asimetri', models.BooleanField(default=False)),
                ('skor_trunk', models.FloatField(blank=True, null=True)),
                ('skor_postur', models.FloatField(blank=True, null=True)),
                ('skor_napas', models.FloatField(blank=True, null=True)),
                ('total_skor', models.FloatField(default=0)),
                ('predikat', models.CharField(blank=True, max_length=15)),
                ('rekomendasi', models.TextField(blank=True)),
                ('pilar_terendah', models.CharField(blank=True, max_length=50)),
                ('catatan_pelatih', models.TextField(blank=True)),
                ('atlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l1_sepakbola', to='combat.atlet')),
            ],
            options={
                'db_table': 'sepakbola_correction_audit_l1',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PowerAuditL3SB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_usia', models.CharField(choices=[('YOUTH', 'Youth (6-12)'), ('JUNIOR', 'Junior (13-17)'), ('SENIOR', 'Senior (18-35)'), ('ELITE', 'Elite')], max_length=10)),
                ('gender', models.CharField(choices=[('PUTRA', 'Putra'), ('PUTRI', 'Putri')], max_length=10)),
                ('tanggal_tes', models.DateField(auto_now_add=True)),
                ('vertical_jump_cm', models.FloatField(blank=True, null=True)),
                ('standing_long_jump_cm', models.FloatField(blank=True, null=True)),
                ('sprint_10m_detik', models.FloatField(blank=True, null=True)),
                ('skor_vertical', models.FloatField(default=0)),
                ('skor_long_jump', models.FloatField(default=0)),
                ('skor_sprint', models.FloatField(default=0)),
                ('total_skor', models.FloatField(default=0)),
                ('pilar_terendah', models.CharField(blank=True, max_length=50)),
                ('catatan_pelatih', models.TextField(blank=True)),
                ('atlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l3_sepakbola', to='combat.atlet')),
            ],
            options={
                'db_table': 'sepakbola_power_audit_l3',
                'ordering': ['-tanggal_tes'],
            },
        ),
        migrations.CreateModel(
            name='SpeedAgilityAuditL4SB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_usia', models.CharField(choices=[('YOUTH', 'Youth (6-12)'), ('JUNIOR', 'Junior (13-17)'), ('SENIOR', 'Senior (18-35)'), ('ELITE', 'Elite')], max_length=10)),
                ('gender', models.CharField(choices=[('PUTRA', 'Putra'), ('PUTRI', 'Putri')], max_length=10)),
                ('tanggal_tes', models.DateField(auto_now_add=True)),
                ('sprint_30m_detik', models.FloatField(blank=True, null=True)),
                ('illinois_agility_detik', models.FloatField(blank=True, null=True)),
                ('yoyo_ir1_level', models.FloatField(blank=True, null=True)),
                ('skor_sprint', models.FloatField(default=0)),
                ('skor_agility', models.FloatField(default=0)),
                ('skor_yoyo', models.FloatField(default=0)),
                ('total_skor', models.FloatField(default=0)),
                ('pilar_terendah', models.CharField(blank=True, max_length=50)),
                ('catatan_pelatih', models.TextField(blank=True)),
                ('atlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l4_sepakbola', to='combat.atlet')),
            ],
            options={
                'db_table': 'sepakbola_speedagility_audit_l4',
                'ordering': ['-tanggal_tes'],
            },
        ),
        migrations.CreateModel(
            name='StrengthAuditL2SB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_usia', models.CharField(choices=[('YOUTH', 'Youth (6-12)'), ('JUNIOR', 'Junior (13-17)'), ('SENIOR', 'Senior (18-35)'), ('ELITE', 'Elite')], max_length=10)),
                ('gender', models.CharField(choices=[('PUTRA', 'Putra'), ('PUTRI', 'Putri')], max_length=10)),
                ('tanggal_tes', models.DateField(auto_now_add=True)),
                ('squat_1rm_kg', models.FloatField(blank=True, null=True)),
                ('berat_badan_kg', models.FloatField(blank=True, null=True)),
                ('single_leg_press_kiri_kg', models.FloatField(blank=True, null=True)),
                ('single_leg_press_kanan_kg', models.FloatField(blank=True, null=True)),
                ('plank_hold_detik', models.FloatField(blank=True, null=True)),
                ('skor_squat', models.FloatField(default=0)),
                ('skor_single_leg', models.FloatField(default=0)),
                ('skor_core', models.FloatField(default=0)),
                ('total_skor', models.FloatField(default=0)),
                ('pilar_terendah', models.CharField(blank=True, max_length=50)),
                ('catatan_pelatih', models.TextField(blank=True)),
                ('atlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l2_sepakbola', to='combat.atlet')),
            ],
            options={
                'db_table': 'sepakbola_strength_audit_l2',
                'ordering': ['-tanggal_tes'],
            },
        ),
    ]
