# Generated by Django 6.0.4 on 2026-09-15 00:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepakbola', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strengthauditl2sb',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='strengthauditl2sb',
            old_name='plank_hold_detik',
            new_name='core_durasi_detik',
        ),
        migrations.RenameField(
            model_name='strengthauditl2sb',
            old_name='single_leg_press_kanan_kg',
            new_name='iso_durasi_detik',
        ),
        migrations.RenameField(
            model_name='strengthauditl2sb',
            old_name='single_leg_press_kiri_kg',
            new_name='iso_tremor_onset_detik',
        ),
        migrations.RenameField(
            model_name='strengthauditl2sb',
            old_name='squat_1rm_kg',
            new_name='lower_5rm_kg',
        ),
        migrations.RemoveField(
            model_name='strengthauditl2sb',
            name='skor_core',
        ),
        migrations.RemoveField(
            model_name='strengthauditl2sb',
            name='skor_single_leg',
        ),
        migrations.RemoveField(
            model_name='strengthauditl2sb',
            name='skor_squat',
        ),
        migrations.RemoveField(
            model_name='strengthauditl2sb',
            name='tanggal_tes',
        ),
        migrations.AddField(
            model_name='strengthauditl2sb',
            name='kena_penalti_asimetri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strengthauditl2sb',
            name='posterior_5rm_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strengthauditl2sb',
            name='predikat',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='strengthauditl2sb',
            name='score_core',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strengthauditl2sb',
            name='score_isometric',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strengthauditl2sb',
            name='score_lower',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strengthauditl2sb',
            name='score_posterior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strengthauditl2sb',
            name='score_singleleg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strengthauditl2sb',
            name='singleleg_kanan_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strengthauditl2sb',
            name='singleleg_kiri_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strengthauditl2sb',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
