# Generated by Django 6.0.4 on 2026-09-15 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepakbola', '0002_alter_strengthauditl2sb_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powerauditl3sb',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='powerauditl3sb',
            old_name='sprint_10m_detik',
            new_name='agility_ttest_detik',
        ),
        migrations.RenameField(
            model_name='powerauditl3sb',
            old_name='standing_long_jump_cm',
            new_name='broad_jump_m',
        ),
        migrations.RenameField(
            model_name='powerauditl3sb',
            old_name='vertical_jump_cm',
            new_name='jump_height_cm',
        ),
        migrations.RemoveField(
            model_name='powerauditl3sb',
            name='skor_long_jump',
        ),
        migrations.RemoveField(
            model_name='powerauditl3sb',
            name='skor_sprint',
        ),
        migrations.RemoveField(
            model_name='powerauditl3sb',
            name='skor_vertical',
        ),
        migrations.RemoveField(
            model_name='powerauditl3sb',
            name='tanggal_tes',
        ),
        migrations.AddField(
            model_name='powerauditl3sb',
            name='predikat',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='powerauditl3sb',
            name='rsi_contact_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerauditl3sb',
            name='rsi_jump_height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerauditl3sb',
            name='rsi_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerauditl3sb',
            name='score_agility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerauditl3sb',
            name='score_broad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerauditl3sb',
            name='score_jump',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerauditl3sb',
            name='score_rsi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerauditl3sb',
            name='score_sprint',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerauditl3sb',
            name='sprint_30m_detik',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerauditl3sb',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
