# Generated by Django 6.0.4 on 2026-09-15 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepakbola', '0003_alter_powerauditl3sb_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speedagilityauditl4sb',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='speedagilityauditl4sb',
            old_name='illinois_agility_detik',
            new_name='hex_avg',
        ),
        migrations.RenameField(
            model_name='speedagilityauditl4sb',
            old_name='sprint_30m_detik',
            new_name='hex_waktu_putaran1',
        ),
        migrations.RenameField(
            model_name='speedagilityauditl4sb',
            old_name='yoyo_ir1_level',
            new_name='hex_waktu_putaran2',
        ),
        migrations.RemoveField(
            model_name='speedagilityauditl4sb',
            name='skor_agility',
        ),
        migrations.RemoveField(
            model_name='speedagilityauditl4sb',
            name='skor_sprint',
        ),
        migrations.RemoveField(
            model_name='speedagilityauditl4sb',
            name='skor_yoyo',
        ),
        migrations.RemoveField(
            model_name='speedagilityauditl4sb',
            name='tanggal_tes',
        ),
        migrations.AddField(
            model_name='speedagilityauditl4sb',
            name='hex_waktu_putaran3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedagilityauditl4sb',
            name='kondisi_uji',
            field=models.CharField(default='FRESH', max_length=20),
        ),
        migrations.AddField(
            model_name='speedagilityauditl4sb',
            name='ladder_postur_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='speedagilityauditl4sb',
            name='ladder_touch_10s',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedagilityauditl4sb',
            name='predikat',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='speedagilityauditl4sb',
            name='score_hex',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedagilityauditl4sb',
            name='score_ladder',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedagilityauditl4sb',
            name='score_yoyo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedagilityauditl4sb',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speedagilityauditl4sb',
            name='vo2max_estimasi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedagilityauditl4sb',
            name='yoyo_level_tercapai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedagilityauditl4sb',
            name='yoyo_shuttle_tercapai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedagilityauditl4sb',
            name='yoyo_total_jarak_m',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
