# Generated by Django 6.0.4 on 2026-08-30 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combat', '0016_seed_cabor_data'),
        ('periodization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_latihan', models.CharField(max_length=150)),
                ('kategori', models.CharField(choices=[('L1', 'L1 - Koreksi (Mobility/Stability)'), ('L2', 'L2 - Kekuatan (Strength)'), ('L3', 'L3 - Power (Plyometric/RFD)'), ('L4', 'L4 - Kecepatan & Reaktif (Speed/Agility)')], max_length=2)),
                ('sub_kategori', models.CharField(blank=True, help_text="mis. 'Ankle Mobility', 'Upper Body Strength'", max_length=100)),
                ('deskripsi', models.TextField(blank=True, help_text='Cara melakukan gerakan')),
                ('video_url', models.URLField(blank=True, help_text='Link video peragaan (YouTube, dll)')),
                ('default_set', models.PositiveIntegerField(blank=True, null=True)),
                ('default_reps', models.CharField(blank=True, help_text="mis. '8-12', '30 detik', 'AMRAP'", max_length=30)),
                ('default_rest_detik', models.PositiveIntegerField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('cabor', models.ForeignKey(blank=True, help_text='Kosongkan kalau gerakan ini generik/berlaku semua cabor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_bank', to='combat.cabor')),
            ],
            options={
                'verbose_name': 'Bank Latihan',
                'verbose_name_plural': 'Bank Latihan',
                'ordering': ['kategori', 'nama_latihan'],
            },
        ),
        migrations.CreateModel(
            name='AutoPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari_ke', models.PositiveSmallIntegerField(choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, "Jum'at"), (6, 'Sabtu'), (7, 'Minggu')], help_text='Hari ke berapa dalam minggu ini')),
                ('set_diberikan', models.PositiveIntegerField(blank=True, null=True)),
                ('reps_diberikan', models.CharField(blank=True, max_length=30)),
                ('rest_diberikan_detik', models.PositiveIntegerField(blank=True, null=True)),
                ('catatan_pelatih', models.TextField(blank=True)),
                ('selesai', models.BooleanField(default=False, help_text='Sudah dikerjakan atlet?')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('micro_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_latihan', to='periodization.microcycle')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penugasan', to='workout_prescription.exercisebank')),
            ],
            options={
                'verbose_name': 'Preskripsi Latihan Harian',
                'verbose_name_plural': 'Preskripsi Latihan Harian',
                'ordering': ['micro_cycle', 'hari_ke'],
            },
        ),
    ]
