# Generated by Django 6.0.4 on 2026-08-30 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combat', '0016_seed_cabor_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField(help_text='Ceritakan kendala/proyek/pertanyaan kamu')),
                ('kategori', models.CharField(choices=[('kendala', 'Kendala Latihan'), ('proyek', 'Proyek / Riset'), ('diskusi', 'Diskusi Umum'), ('minta_saran', 'Minta Saran Intervensi')], default='diskusi', max_length=20)),
                ('radar_data_snapshot', models.JSONField(blank=True, help_text="Snapshot skor L1-L4 (sudah dianonimkan), mis. {'l1': 7.2, 'l2': 6.5, 'l3': 5.8, 'l4': 6.0}", null=True)),
                ('status', models.CharField(choices=[('TERBUKA', 'Terbuka'), ('TERJAWAB', 'Sudah Terjawab'), ('DITUTUP', 'Ditutup')], default='TERBUKA', max_length=10)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('atlet_terkait', models.ForeignKey(blank=True, help_text='Referensi INTERNAL penulis saja -- JANGAN pernah ditampilkan ke pelatih lain di UI', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_posts_terkait', to='combat.atlet')),
                ('cabor', models.ForeignKey(blank=True, help_text='Opsional, tag cabor yang relevan sama postingan ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_posts', to='combat.cabor')),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Komunitas Pelatih',
                'verbose_name_plural': 'Post Komunitas Pelatih',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='PostSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('diterima', models.BooleanField(default=False, help_text='Ditandai sebagai solusi terbaik oleh penulis post')),
                ('poin_diberikan', models.PositiveIntegerField(default=0, help_text='Poin reputasi yang didapat penulis solusi ini kalau diterima')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_solutions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solusi', to='coaching_community.coachpost')),
            ],
            options={
                'verbose_name': 'Solusi/Balasan Post',
                'verbose_name_plural': 'Solusi/Balasan Post',
                'ordering': ['-diterima', 'dibuat_pada'],
            },
        ),
    ]
