# Generated by Django 6.0.4 on 2026-05-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramLatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('correction', 'Koreksi Teknik'), ('strength', 'Kekuatan'), ('power', 'Power')], max_length=20)),
                ('deskripsi', models.TextField(blank=True)),
                ('tanggal', models.DateField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Program Latihan',
                'verbose_name_plural': 'Program Latihan',
                'ordering': ['-tanggal'],
            },
        ),
    ]
