# Generated by Django 6.0.4 on 2026-05-31 01:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0002_atlet_correctionauditl1_powerauditl3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedAgilityAuditL4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atlet_name', models.CharField(blank=True, max_length=150, verbose_name='Nama Atlet (form)')),
                ('kategori_usia', models.CharField(choices=[('ELITE', 'Elite'), ('YOUTH', 'Youth'), ('JUNIOR', 'Junior'), ('SENIOR', 'Senior')], default='ELITE', max_length=20)),
                ('gender', models.CharField(choices=[('Putra', 'Putra'), ('Putri', 'Putri')], default='Putra', max_length=10)),
                ('kelas_berat', models.FloatField(blank=True, null=True, verbose_name='Berat Badan (kg)')),
                ('hex_waktu_putaran1', models.FloatField(blank=True, null=True, verbose_name='Hex Jump Putaran 1 (detik)')),
                ('hex_waktu_putaran2', models.FloatField(blank=True, null=True, verbose_name='Hex Jump Putaran 2 (detik)')),
                ('hex_waktu_putaran3', models.FloatField(blank=True, null=True, verbose_name='Hex Jump Putaran 3 (detik)')),
                ('hex_waktu_rata', models.FloatField(blank=True, help_text='Dihitung otomatis dari 3 putaran', null=True, verbose_name='Hex Jump Rata-rata (detik)')),
                ('score_hex', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Hexagon Jump (0-10)')),
                ('punch_freq_10s', models.IntegerField(blank=True, null=True, verbose_name='Jumlah Pukulan dalam 10 Detik')),
                ('punch_postur_ok', models.BooleanField(default=True, verbose_name='Postur Tinju Tetap Benar')),
                ('punch_reaction_time_ms', models.FloatField(blank=True, help_text='Waktu reaksi dari stimulus ke pukulan pertama', null=True, verbose_name='Reaction Time (ms)')),
                ('score_punch', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Punch Frequency (0-10)')),
                ('yoyo_level_tercapai', models.IntegerField(blank=True, null=True, verbose_name='Level Yo-Yo IR1 Tercapai')),
                ('yoyo_shuttle_tercapai', models.IntegerField(blank=True, null=True, verbose_name='Shuttle Yo-Yo IR1 Tercapai')),
                ('yoyo_total_jarak_m', models.FloatField(blank=True, help_text='Dihitung otomatis dari level & shuttle', null=True, verbose_name='Total Jarak Yo-Yo (meter)')),
                ('yoyo_vo2max_estimasi', models.FloatField(blank=True, help_text='Formula: VO2max = (jarak × 0.0084) + 36.4', null=True, verbose_name='Estimasi VO2 Max (mL/kg/min)')),
                ('score_yoyo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Yo-Yo IR1 (0-10)')),
                ('kondisi_uji', models.CharField(choices=[('FRESH', 'Fresh — Tanpa Pre-fatigue'), ('POST_SPARRING', 'Post-Sparring — Setelah Sparring 3 Ronde'), ('POST_CIRCUIT', 'Post-Circuit — Setelah Circuit Training')], default='FRESH', max_length=50, verbose_name='Kondisi Saat Uji')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Coach')),
                ('total_skor', models.FloatField(default=0, verbose_name='Total Skor')),
                ('predikat', models.CharField(choices=[('ELITE', 'Elite — Siap Kompetisi'), ('READY', 'Ready — Layak Bertahan L4'), ('DEVELOPING', 'Developing — Perlu Peningkatan'), ('NOVICE', 'Novice — Kembali ke L3')], default='NOVICE', max_length=20)),
                ('layak_kompetisi', models.BooleanField(default=False)),
                ('layak_bertahan', models.BooleanField(default=False)),
                ('rekomendasi_auto', models.TextField(blank=True)),
                ('alasan_tidak_layak', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('atlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_l4', to='combat.atlet', verbose_name='Atlet')),
            ],
            options={
                'verbose_name': 'Audit L4 — Speed & Agility',
                'verbose_name_plural': 'Audit L4 — Speed & Agility',
                'ordering': ['-timestamp'],
            },
        ),
    ]
