# Generated by Django 6.0.4 on 2026-06-01 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0003_speedagilityauditl4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speedagilityauditl4',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit L4 â€” Speed & Agility', 'verbose_name_plural': 'Audit L4 â€” Speed & Agility'},
        ),
        migrations.AlterField(
            model_name='atlet',
            name='tahap_ltad',
            field=models.CharField(blank=True, choices=[('fundamental', 'FUNdamental (6â€“9 thn)'), ('learn_train', 'Learn to Train (9â€“12 thn)'), ('train_train', 'Train to Train (12â€“16 thn)'), ('train_compete', 'Train to Compete (16â€“19 thn)'), ('train_win', 'Train to Win (19+ thn)'), ('active_life', 'Active for Life')], max_length=20, verbose_name='Tahap LTAD'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1',
            name='score_breathing',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Pernafasan (0â€“10)'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1',
            name='score_extension',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Ekstensi (0â€“10)'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1',
            name='score_posture',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Postur (0â€“10)'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1',
            name='score_rotation',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Rotasi (0â€“10)'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1',
            name='score_stability',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Stabilitas (0â€“10)'),
        ),
        migrations.AlterField(
            model_name='rekomendasiprogram',
            name='audit_level',
            field=models.CharField(choices=[('L1', 'L1 â€” Correction'), ('L2', 'L2 â€” Strength'), ('L3', 'L3 â€” Power')], max_length=2, verbose_name='Berdasarkan Audit'),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='kondisi_uji',
            field=models.CharField(choices=[('FRESH', 'Fresh â€” Tanpa Pre-fatigue'), ('POST_SPARRING', 'Post-Sparring â€” Setelah Sparring 3 Ronde'), ('POST_CIRCUIT', 'Post-Circuit â€” Setelah Circuit Training')], default='FRESH', max_length=50, verbose_name='Kondisi Saat Uji'),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='predikat',
            field=models.CharField(choices=[('ELITE', 'Elite â€” Siap Kompetisi'), ('READY', 'Ready â€” Layak Bertahan L4'), ('DEVELOPING', 'Developing â€” Perlu Peningkatan'), ('NOVICE', 'Novice â€” Kembali ke L3')], default='NOVICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='yoyo_vo2max_estimasi',
            field=models.FloatField(blank=True, help_text='Formula: VO2max = (jarak Ã— 0.0084) + 36.4', null=True, verbose_name='Estimasi VO2 Max (mL/kg/min)'),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='iso_tremor_rasio',
            field=models.FloatField(blank=True, help_text='tremor_onset / total_durasi Ã— 100. Makin tinggi = CNS makin segar.', null=True, verbose_name='Tremor Onset Ratio (%)'),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='score_core',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Core (0â€“10)'),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='score_isometric',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Isometric (0â€“10)'),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='score_lower',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Lower (0â€“10)'),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='score_pull',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Pull (0â€“10)'),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='score_push',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Push (0â€“10)'),
        ),
    ]
