# Generated by Django 6.0.4 on 2026-06-10 08:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0004_alter_speedagilityauditl4_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speedagilityauditl4',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit L4 — Speed & Agility', 'verbose_name_plural': 'Audit L4 — Speed & Agility'},
        ),
        migrations.AddField(
            model_name='atlet',
            name='pelatih',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atlet_binaan', to=settings.AUTH_USER_MODEL, verbose_name='Pelatih'),
        ),
        migrations.AlterField(
            model_name='atlet',
            name='tahap_ltad',
            field=models.CharField(blank=True, choices=[('fundamental', 'FUNdamental (6-9 thn)'), ('learn_train', 'Learn to Train (9-12 thn)'), ('train_train', 'Train to Train (12-16 thn)'), ('train_compete', 'Train to Compete (16-19 thn)'), ('train_win', 'Train to Win (19+ thn)'), ('active_life', 'Active for Life')], max_length=20, verbose_name='Tahap LTAD'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1',
            name='alasan_tidak_layak',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='correctionauditl1',
            name='atlet_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nama Atlet (form)'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1',
            name='layak_naik',
            field=models.BooleanField(default=False, verbose_name='Layak Naik ke L2?'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1',
            name='predikat',
            field=models.CharField(choices=[('ELITE', 'Elite'), ('READY', 'Ready'), ('DEVELOPING', 'Developing'), ('NOVICE', 'Novice')], default='NOVICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='correctionauditl1',
            name='score_breathing',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Pernafasan'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1',
            name='score_extension',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Ekstensi'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1',
            name='score_posture',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Postur'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1',
            name='score_rotation',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Rotasi'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1',
            name='score_stability',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Stabilitas'),
        ),
        migrations.AlterField(
            model_name='powerauditl3',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powerauditl3',
            name='ai_rep_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powerauditl3',
            name='alasan_tidak_layak',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='powerauditl3',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powerauditl3',
            name='kelas_berat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powerauditl3',
            name='layak_bertahan',
            field=models.BooleanField(default=False, verbose_name='Layak Bertahan di L3?'),
        ),
        migrations.AlterField(
            model_name='powerauditl3',
            name='layak_naik',
            field=models.BooleanField(default=False, verbose_name='Layak Kompetisi?'),
        ),
        migrations.AlterField(
            model_name='powerauditl3',
            name='rsi_contact_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powerauditl3',
            name='rsi_jump_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powerauditl3',
            name='rsi_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powerauditl3',
            name='score_agility',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='powerauditl3',
            name='score_jump',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='powerauditl3',
            name='score_rsi',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='powerauditl3',
            name='score_sprint',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='powerauditl3',
            name='score_throw',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='powerauditl3',
            name='total_skor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rekomendasiprogram',
            name='atlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekomendasi', to='combat.atlet'),
        ),
        migrations.AlterField(
            model_name='rekomendasiprogram',
            name='audit_level',
            field=models.CharField(choices=[('L1', 'L1 — Correction'), ('L2', 'L2 — Strength'), ('L3', 'L3 — Power')], max_length=2),
        ),
        migrations.AlterField(
            model_name='rekomendasiprogram',
            name='durasi_minggu',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='rekomendasiprogram',
            name='isi_rekomendasi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rekomendasiprogram',
            name='sudah_dijalankan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='atlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_l4', to='combat.atlet'),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='atlet_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='catatan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='hex_waktu_putaran1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='hex_waktu_putaran2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='hex_waktu_putaran3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='hex_waktu_rata',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='kelas_berat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='kondisi_uji',
            field=models.CharField(choices=[('FRESH', 'Fresh — Tanpa Pre-fatigue'), ('POST_SPARRING', 'Post-Sparring — Setelah Sparring 3 Ronde'), ('POST_CIRCUIT', 'Post-Circuit — Setelah Circuit Training')], default='FRESH', max_length=50),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='predikat',
            field=models.CharField(choices=[('ELITE', 'Elite'), ('READY', 'Ready'), ('DEVELOPING', 'Developing'), ('NOVICE', 'Novice')], default='NOVICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='punch_freq_10s',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='punch_postur_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='punch_reaction_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='score_hex',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='score_punch',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='score_yoyo',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='total_skor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='yoyo_level_tercapai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='yoyo_shuttle_tercapai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='yoyo_total_jarak_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='yoyo_vo2max_estimasi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='ai_rep_count_lower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='ai_rep_count_pull',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='ai_rep_count_push',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='alasan_tidak_layak',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='iso_durasi_detik',
            field=models.IntegerField(blank=True, null=True, verbose_name='Split Squat Hold (detik)'),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='iso_tremor_onset_detik',
            field=models.IntegerField(blank=True, null=True, verbose_name='Onset Tremor (detik)'),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='iso_tremor_rasio',
            field=models.FloatField(blank=True, null=True, verbose_name='Tremor Onset Ratio (%)'),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='layak_naik',
            field=models.BooleanField(default=False, verbose_name='Layak Naik ke L3?'),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='lower_5rm_beban',
            field=models.FloatField(blank=True, null=True, verbose_name='Lower 5RM Beban (kg)'),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='lower_5rm_bw_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='5RM / BW Ratio'),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='score_core',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='score_isometric',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='score_lower',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='score_pull',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='score_push',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='total_skor',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ProfilPelatih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabang', models.CharField(blank=True, choices=[('boxing', 'Boxing'), ('silat', 'Pencak Silat'), ('tkd', 'Taekwondo'), ('karate', 'Karate'), ('judo', 'Judo'), ('mma', 'MMA')], max_length=20)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=10)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_pelatih', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Pelatih',
                'verbose_name_plural': 'Profil Pelatih',
            },
        ),
    ]
