# Generated by Django 6.0.4 on 2026-06-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0005_alter_speedagilityauditl4_options_atlet_pelatih_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlet',
            name='cabang',
            field=models.CharField(blank=True, choices=[('boxing', 'Boxing'), ('muaythai', 'Muay Thai'), ('tkd', 'Taekwondo'), ('karate', 'Karate'), ('judo', 'Judo'), ('mma', 'MMA')], max_length=20, verbose_name='Cabang Olahraga'),
        ),
        migrations.AlterField(
            model_name='profilpelatih',
            name='cabang',
            field=models.CharField(blank=True, choices=[('boxing', 'Boxing'), ('muaythai', 'Muay Thai'), ('tkd', 'Taekwondo'), ('karate', 'Karate'), ('judo', 'Judo'), ('mma', 'MMA')], max_length=20),
        ),
    ]
