# Generated by Django 6.0.4 on 2026-06-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0006_alter_atlet_cabang_alter_profilpelatih_cabang'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilpelatih',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='profilpelatih',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_pelatih/', verbose_name='Foto Profil'),
        ),
    ]
