# Generated by Django 6.0.4 on 2026-07-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0007_profilpelatih_email_profilpelatih_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctionauditl1',
            options={'ordering': ['-timestamp'], 'verbose_name': 'L1 - Correction', 'verbose_name_plural': 'L1 - Correction'},
        ),
        migrations.AlterModelOptions(
            name='powerauditl3',
            options={'ordering': ['-timestamp'], 'verbose_name': 'L3 - Power', 'verbose_name_plural': 'L3 - Power'},
        ),
        migrations.AlterModelOptions(
            name='speedagilityauditl4',
            options={'ordering': ['-timestamp'], 'verbose_name': 'L4 - Speed & Agility', 'verbose_name_plural': 'L4 - Speed & Agility'},
        ),
        migrations.AlterModelOptions(
            name='strengthauditl2',
            options={'ordering': ['-timestamp'], 'verbose_name': 'L2 - Strength', 'verbose_name_plural': 'L2 - Strength'},
        ),
    ]
