# Generated by Django 6.0.4 on 2026-07-19 06:02
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0008_alter_correctionauditl1_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlet',
            name='cabang',
            field=models.CharField(blank=True, choices=[('boxing', 'Boxing'), ('muaythai', 'Muay Thai'), ('tkd', 'Taekwondo')], max_length=20, verbose_name='Cabang Olahraga'),
        ),
        migrations.AlterField(
            model_name='profilpelatih',
            name='cabang',
            field=models.CharField(blank=True, choices=[('boxing', 'Boxing'), ('muaythai', 'Muay Thai'), ('tkd', 'Taekwondo')], max_length=20),
        ),
    ]
