# Generated by Django 6.0.4 on 2026-08-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0009_alter_atlet_cabang_alter_profilpelatih_cabang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlet',
            name='cabang',
            field=models.CharField(blank=True, choices=[('boxing', 'Boxing'), ('muaythai', 'Muay Thai'), ('tkd', 'Taekwondo'), ('krt', 'Karate')], max_length=20, verbose_name='Cabang Olahraga'),
        ),
        migrations.AlterField(
            model_name='profilpelatih',
            name='cabang',
            field=models.CharField(blank=True, choices=[('boxing', 'Boxing'), ('muaythai', 'Muay Thai'), ('tkd', 'Taekwondo'), ('krt', 'Karate')], max_length=20),
        ),
    ]
