# Generated by Django 6.0.4 on 2026-08-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0010_alter_atlet_cabang_alter_profilpelatih_cabang'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilpelatih',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio Singkat'),
        ),
        migrations.AddField(
            model_name='profilpelatih',
            name='sertifikasi',
            field=models.TextField(blank=True, help_text='Satu baris per sertifikasi', verbose_name='Sertifikasi & Lisensi'),
        ),
    ]
