# Generated by Django 6.0.4 on 2026-08-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0011_profilpelatih_bio_profilpelatih_sertifikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerauditl3',
            name='agility_ttest_detik',
            field=models.FloatField(blank=True, null=True, verbose_name='Agility T-Test (detik)'),
        ),
        migrations.AddField(
            model_name='powerauditl3',
            name='jump_height_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Tinggi Lompatan (cm)'),
        ),
        migrations.AddField(
            model_name='powerauditl3',
            name='sprint_30m_detik',
            field=models.FloatField(blank=True, null=True, verbose_name='Sprint 30M (detik)'),
        ),
        migrations.AddField(
            model_name='powerauditl3',
            name='throw_jarak_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Jarak Lempar (m)'),
        ),
    ]
