# Generated by Django 6.0.4 on 2026-08-14 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0012_powerauditl3_agility_ttest_detik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedagilityauditl4',
            name='kick_freq_10s',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedagilityauditl4',
            name='kick_postur_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='speedagilityauditl4',
            name='kick_reaction_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedagilityauditl4',
            name='score_kick',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
