# Generated by Django 6.0.4 on 2026-08-22 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0013_speedagilityauditl4_kick_freq_10s_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionauditl1',
            name='score_ankle',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skor Ankle Mobility'),
        ),
        migrations.AlterField(
            model_name='correctionauditl1',
            name='layak_naik',
            field=models.BooleanField(default=False, verbose_name='Layak Naikke L2?'),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='layak_naik',
            field=models.BooleanField(default=False, verbose_name='Layak Naikke L3?'),
        ),
        migrations.AlterField(
            model_name='strengthauditl2',
            name='push_5rm_beban',
            field=models.FloatField(blank=True, null=True, verbose_name='Push 5RMBeban (kg)'),
        ),
    ]
