# Generated by Django 6.0.4 on 2026-08-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0014_correctionauditl1_score_ankle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text="Harus sama persis dengan value di CABANG_CHOICES, mis. 'boxing', 'krt', 'tkd'", max_length=20, unique=True)),
                ('nama', models.CharField(max_length=50, verbose_name='Nama Cabor')),
                ('app_slug', models.CharField(blank=True, help_text="Nama app Django-nya, mis. 'karate' (beda dari kode 'krt'). Kosongkan kalau app-nya belum ada.", max_length=30)),
                ('deskripsi', models.TextField(blank=True)),
                ('icon_class', models.CharField(blank=True, help_text="Kelas FontAwesome, mis. 'fa-solid fa-hand-fist'", max_length=50)),
                ('warna_tema', models.CharField(blank=True, default='#e63946', help_text='Kode hex, mis. #e63946', max_length=7)),
                ('aktif', models.BooleanField(default=True, help_text='Non-aktifkan buat sembunyikan dari pilihan tanpa hapus datanya')),
                ('urutan_tampil', models.PositiveIntegerField(default=0)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cabor',
                'verbose_name_plural': 'Cabor',
                'ordering': ['urutan_tampil', 'nama'],
            },
        ),
    ]
