# Generated by Django 6.0.4 on 2026-10-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0018_seed_cabor_sepakbola_basketball'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilpelatih',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=10),
        ),
    ]
