# Generated by Django 6.0.4 on 2026-10-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0019_profilpelatih_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlet',
            name='cabang',
            field=models.CharField(blank=True, choices=[('boxing', 'Boxing'), ('muaythai', 'Muay Thai'), ('tkd', 'Taekwondo'), ('krt', 'Karate'), ('sepakbola', 'Sepak Bola'), ('basketball', 'Bola Basket')], max_length=20, verbose_name='Cabang Olahraga'),
        ),
        migrations.AlterField(
            model_name='profilpelatih',
            name='cabang',
            field=models.CharField(blank=True, choices=[('boxing', 'Boxing'), ('muaythai', 'Muay Thai'), ('tkd', 'Taekwondo'), ('krt', 'Karate'), ('sepakbola', 'Sepak Bola'), ('basketball', 'Bola Basket')], max_length=20),
        ),
    ]
