# Generated by Django 6.0.4 on 2026-10-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0020_alter_atlet_cabang_alter_profilpelatih_cabang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilpelatih',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='approved', max_length=10),
        ),
    ]
