# Generated by Django 6.0.4 on 2026-10-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0021_alter_profilpelatih_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilpelatih',
            name='tier',
        ),
        migrations.AlterField(
            model_name='rekomendasiprogram',
            name='audit_level',
            field=models.CharField(choices=[('L1', 'L1 â€” Correction'), ('L2', 'L2 â€” Strength'), ('L3', 'L3 â€” Power')], max_length=2),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='kondisi_uji',
            field=models.CharField(choices=[('FRESH', 'Fresh â€” Tanpa Pre-fatigue'), ('POST_SPARRING', 'Post-Sparring â€” Setelah Sparring 3 Ronde'), ('POST_CIRCUIT', 'Post-Circuit â€” Setelah Circuit Training')], default='FRESH', max_length=50),
        ),
    ]
