# Generated by Django 6.0.4 on 2026-10-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0022_remove_profilpelatih_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekomendasiprogram',
            name='audit_level',
            field=models.CharField(choices=[('L1', 'L1 — Correction'), ('L2', 'L2 — Strength'), ('L3', 'L3 — Power')], max_length=2),
        ),
        migrations.AlterField(
            model_name='speedagilityauditl4',
            name='kondisi_uji',
            field=models.CharField(choices=[('FRESH', 'Fresh — Tanpa Pre-fatigue'), ('POST_SPARRING', 'Post-Sparring — Setelah Sparring 3 Ronde'), ('POST_CIRCUIT', 'Post-Circuit — Setelah Circuit Training')], default='FRESH', max_length=50),
        ),
    ]
