# Generated by Django 6.0.4 on 2026-08-09 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(choices=[('permainan_olahraga', 'Permainan dan Olahraga'), ('senam', 'Aktivitas Senam'), ('gerak_berirama', 'Aktivitas Gerak Berirama'), ('air', 'Aktivitas Permainan dan Olahraga Air'), ('kebugaran', 'Aktivitas Kebugaran Jasmani')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuruProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('sekolah', models.CharField(max_length=100)),
                ('fase', models.CharField(choices=[('A', 'Fase A (Kelas 1-2 SD)'), ('B', 'Fase B (Kelas 3-4 SD)'), ('C', 'Fase C (Kelas 5-6 SD)'), ('D', 'Fase D (Kelas 7-9 SMP)'), ('E', 'Fase E (Kelas 10 SMA)'), ('F', 'Fase F (Kelas 11-12 SMA)')], max_length=1)),
                ('nip', models.CharField(blank=True, max_length=30)),
                ('tanggal_bergabung', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumenTKJI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('A', 'Fase A (Kelas 1-2 SD)'), ('B', 'Fase B (Kelas 3-4 SD)'), ('C', 'Fase C (Kelas 5-6 SD)'), ('D', 'Fase D (Kelas 7-9 SMP)'), ('E', 'Fase E (Kelas 10 SMA)'), ('F', 'Fase F (Kelas 11-12 SMA)')], max_length=1)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('lari_jarak_pendek_m', models.IntegerField(default=50)),
                ('gantung_durasi_detik', models.IntegerField(help_text='Gantung siku tekuk / gantung angkat tubuh')),
                ('sit_up_durasi_detik', models.IntegerField(default=60)),
                ('lari_jarak_menengah_m', models.IntegerField(help_text='600 / 1000 / 1200 tergantung fase')),
            ],
            options={
                'unique_together': {('fase', 'jenis_kelamin')},
            },
        ),
        migrations.CreateModel(
            name='MateriFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('A', 'Fase A (Kelas 1-2 SD)'), ('B', 'Fase B (Kelas 3-4 SD)'), ('C', 'Fase C (Kelas 5-6 SD)'), ('D', 'Fase D (Kelas 7-9 SMP)'), ('E', 'Fase E (Kelas 10 SMA)'), ('F', 'Fase F (Kelas 11-12 SMA)')], max_length=1)),
                ('nama_materi', models.CharField(max_length=100)),
                ('deskripsi_cp', models.TextField(blank=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi', to='pjok.kategoriaktivitas')),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=20)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tanggal_lahir', models.DateField()),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa', to='pjok.guruprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PenilaianTeknik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.FloatField()),
                ('catatan', models.TextField(blank=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_teknik', to='pjok.materifase')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_teknik', to='pjok.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='PenilaianKarakter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspek', models.CharField(choices=[('sportivitas', 'Sportivitas'), ('kerjasama', 'Kerja Sama'), ('disiplin', 'Disiplin'), ('tanggung_jawab', 'Tanggung Jawab'), ('percaya_diri', 'Percaya Diri')], max_length=30)),
                ('skor', models.FloatField()),
                ('catatan', models.TextField(blank=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_karakter', to='pjok.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='PenilaianFisik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_tes', models.DateField(auto_now_add=True)),
                ('plank_hold_detik', models.FloatField(help_text='Durasi plank (detik)')),
                ('sit_and_reach_cm', models.FloatField(help_text='Fleksibilitas (cm)')),
                ('gantung_durasi_tercapai_detik', models.FloatField()),
                ('sit_up_repetisi', models.IntegerField()),
                ('vertical_jump_cm', models.FloatField()),
                ('standing_broad_jump_cm', models.FloatField(blank=True, null=True)),
                ('lari_cepat_detik', models.FloatField(help_text='Waktu tempuh lari jarak pendek TKJI')),
                ('lari_menengah_detik', models.FloatField(help_text='Waktu tempuh lari jarak menengah TKJI')),
                ('skor_l1', models.FloatField(blank=True, editable=False, null=True)),
                ('skor_l2', models.FloatField(blank=True, editable=False, null=True)),
                ('skor_l3', models.FloatField(blank=True, editable=False, null=True)),
                ('skor_l4', models.FloatField(blank=True, editable=False, null=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_fisik', to='pjok.siswa')),
            ],
        ),
    ]
