# Generated by Django 6.0.4 on 2026-08-12 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjok', '0002_seed_kategori_aktivitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='penilaiankarakter',
            name='tingkat',
            field=models.IntegerField(blank=True, choices=[(1, 'Perlu Bimbingan'), (2, 'Cukup'), (3, 'Baik'), (4, 'Sangat Baik')], null=True),
        ),
        migrations.AddField(
            model_name='penilaianteknik',
            name='tingkat',
            field=models.IntegerField(blank=True, choices=[(1, 'Perlu Bimbingan'), (2, 'Cukup'), (3, 'Baik'), (4, 'Sangat Baik')], null=True),
        ),
        migrations.AlterField(
            model_name='penilaiankarakter',
            name='skor',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='penilaianteknik',
            name='skor',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='PenilaianPengetahuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.IntegerField(choices=[(1, 'Perlu Bimbingan'), (2, 'Cukup'), (3, 'Baik'), (4, 'Sangat Baik')])),
                ('skor', models.FloatField(blank=True, editable=False, null=True)),
                ('catatan', models.TextField(blank=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_pengetahuan', to='pjok.siswa')),
            ],
        ),
    ]
