# Generated by Django 6.0.4 on 2026-08-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjok', '0003_penilaiankarakter_tingkat_penilaianteknik_tingkat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='fase',
            field=models.CharField(blank=True, choices=[('A', 'Fase A (Kelas 1-2 SD)'), ('B', 'Fase B (Kelas 3-4 SD)'), ('C', 'Fase C (Kelas 5-6 SD)'), ('D', 'Fase D (Kelas 7-9 SMP)'), ('E', 'Fase E (Kelas 10 SMA)'), ('F', 'Fase F (Kelas 11-12 SMA)')], max_length=1, null=True),
        ),
    ]
