# Generated by Django 6.0.4 on 2026-08-13 08:36
from django.db import migrations


def isi_fase_dari_guru(apps, schema_editor):
    Siswa = apps.get_model('pjok', 'Siswa')
    for siswa in Siswa.objects.filter(fase__isnull=True):
        siswa.fase = siswa.guru.fase
        siswa.save(update_fields=['fase'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('pjok', '0004_siswa_fase'),
    ]
    operations = [
        migrations.RunPython(isi_fase_dari_guru, reverse_noop),
    ]