# Generated by Django 6.0.4 on 2026-08-14 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjok', '0005_isi_fase_siswa_lama'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesiAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('A', 'Fase A (Kelas 1-2 SD)'), ('B', 'Fase B (Kelas 3-4 SD)'), ('C', 'Fase C (Kelas 5-6 SD)'), ('D', 'Fase D (Kelas 7-9 SMP)'), ('E', 'Fase E (Kelas 10 SMA)'), ('F', 'Fase F (Kelas 11-12 SMA)')], max_length=1)),
                ('tanggal', models.DateField()),
                ('catatan_sesi', models.CharField(blank=True, help_text='Contoh: Materi lari zig-zag', max_length=200)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_absensi', to='pjok.guruprofile')),
            ],
            options={
                'ordering': ['-tanggal'],
                'unique_together': {('guru', 'fase', 'tanggal')},
            },
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('H', 'Hadir'), ('I', 'Izin'), ('S', 'Sakit'), ('A', 'Alpa')], default='H', max_length=1)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='pjok.siswa')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_absensi', to='pjok.sesiabsensi')),
            ],
            options={
                'unique_together': {('sesi', 'siswa')},
            },
        ),
    ]
