# Generated by Django 6.0.4 on 2026-08-15 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjok', '0006_sesiabsensi_absensi'),
    ]

    operations = [
        migrations.CreateModel(
            name='RencanaMingguan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('A', 'Fase A (Kelas 1-2 SD)'), ('B', 'Fase B (Kelas 3-4 SD)'), ('C', 'Fase C (Kelas 5-6 SD)'), ('D', 'Fase D (Kelas 7-9 SMP)'), ('E', 'Fase E (Kelas 10 SMA)'), ('F', 'Fase F (Kelas 11-12 SMA)')], max_length=1)),
                ('tahun_ajaran', models.CharField(help_text='Contoh: 2026/2027', max_length=9)),
                ('semester', models.CharField(choices=[('ganjil', 'Ganjil'), ('genap', 'Genap')], max_length=6)),
                ('minggu_ke', models.PositiveSmallIntegerField()),
                ('nama_materi_bebas', models.CharField(blank=True, help_text='Isi kalau materi belum ada di daftar Materi Fase', max_length=150)),
                ('alokasi_jp', models.PositiveSmallIntegerField(default=2, help_text='Jumlah jam pelajaran')),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rencana_mingguan', to='pjok.guruprofile')),
                ('materi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rencana_mingguan', to='pjok.materifase')),
            ],
            options={
                'ordering': ['tahun_ajaran', 'semester', 'minggu_ke'],
                'unique_together': {('guru', 'fase', 'tahun_ajaran', 'semester', 'minggu_ke')},
            },
        ),
    ]
