# Generated by Django 6.0.4 on 2026-08-16 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjok', '0007_rencanamingguan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TujuanPembelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('A', 'Fase A (Kelas 1-2 SD)'), ('B', 'Fase B (Kelas 3-4 SD)'), ('C', 'Fase C (Kelas 5-6 SD)'), ('D', 'Fase D (Kelas 7-9 SMP)'), ('E', 'Fase E (Kelas 10 SMA)'), ('F', 'Fase F (Kelas 11-12 SMA)')], max_length=1)),
                ('kode', models.CharField(help_text='Contoh: TP.1.1', max_length=20)),
                ('elemen', models.CharField(choices=[('keterampilan_gerak', 'Keterampilan Gerak'), ('pengetahuan_gerak', 'Pengetahuan Gerak'), ('pemanfaatan_gerak', 'Pemanfaatan Gerak'), ('pengembangan_karakter', 'Pengembangan Karakter')], max_length=30)),
                ('deskripsi', models.TextField(help_text='Rumusan Tujuan Pembelajaran')),
                ('kktp', models.TextField(blank=True, help_text='Kriteria Ketercapaian Tujuan Pembelajaran')),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tujuan_pembelajaran', to='pjok.guruprofile')),
            ],
            options={
                'ordering': ['elemen', 'kode'],
                'unique_together': {('guru', 'fase', 'kode')},
            },
        ),
        migrations.AddField(
            model_name='rencanamingguan',
            name='tp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rencana_mingguan', to='pjok.tujuanpembelajaran'),
        ),
    ]
