# Generated by Django 6.0.4 on 2026-09-02 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjok', '0008_tujuanpembelajaran_rencanamingguan_tp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatatanCedera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_kejadian', models.DateField()),
                ('jenis_cedera', models.CharField(help_text='Contoh: keseleo pergelangan kaki, benturan kepala', max_length=100)),
                ('deskripsi', models.TextField(blank=True, help_text='Kronologi singkat kejadian')),
                ('tindakan_diambil', models.TextField(blank=True, help_text='Pertolongan pertama / rujukan yang diberikan')),
                ('status', models.CharField(choices=[('pemulihan', 'Masih Pemulihan'), ('sembuh', 'Sudah Sembuh'), ('kronis', 'Kondisi Kronis / Berulang')], default='pemulihan', max_length=10)),
                ('dicatat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pjok.guruprofile')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_cedera', to='pjok.siswa')),
            ],
            options={
                'ordering': ['-tanggal_kejadian'],
            },
        ),
        migrations.CreateModel(
            name='KondisiKesehatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golongan_darah', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O'), ('', 'Tidak tahu')], max_length=2)),
                ('alergi', models.TextField(blank=True, help_text='Contoh: alergi debu, alergi makanan tertentu — pisahkan dengan koma')),
                ('riwayat_penyakit', models.TextField(blank=True, help_text='Contoh: asma, jantung bawaan, epilepsi, diabetes')),
                ('kontraindikasi_aktivitas', models.TextField(blank=True, help_text='Aktivitas yang harus dihindari atau dimodifikasi untuk siswa ini')),
                ('obat_darurat', models.CharField(blank=True, help_text='Contoh: Inhaler asma — disimpan di tas siswa', max_length=200)),
                ('kontak_darurat_nama', models.CharField(blank=True, max_length=100)),
                ('kontak_darurat_hubungan', models.CharField(blank=True, help_text='Contoh: Ibu, Ayah, Wali', max_length=50)),
                ('kontak_darurat_telepon', models.CharField(blank=True, max_length=20)),
                ('tingkat_risiko', models.CharField(choices=[('rendah', 'Rendah — aman ikut semua aktivitas'), ('sedang', 'Sedang — perlu pemantauan/penyesuaian tertentu'), ('tinggi', 'Tinggi — perlu penyesuaian aktivitas & pengawasan ketat')], default='rendah', max_length=10)),
                ('catatan_tambahan', models.TextField(blank=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kesehatan', to='pjok.siswa')),
            ],
        ),
    ]
