# Generated by Django 6.0.4 on 2026-09-03 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjok', '0009_catatancedera_kondisikesehatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulAjar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('A', 'Fase A (Kelas 1-2 SD)'), ('B', 'Fase B (Kelas 3-4 SD)'), ('C', 'Fase C (Kelas 5-6 SD)'), ('D', 'Fase D (Kelas 7-9 SMP)'), ('E', 'Fase E (Kelas 10 SMA)'), ('F', 'Fase F (Kelas 11-12 SMA)')], max_length=1)),
                ('judul', models.CharField(help_text='Contoh: Passing Bawah Bola Voli - Pertemuan 1', max_length=150)),
                ('alokasi_waktu', models.CharField(default='2 x 35 menit', help_text='Contoh: 2 x 35 menit', max_length=50)),
                ('pemahaman_bermakna', models.TextField(blank=True, help_text='Manfaat/kebermaknaan materi bagi kehidupan siswa')),
                ('pertanyaan_pemantik', models.TextField(blank=True, help_text='Pertanyaan pembuka untuk memancing rasa ingin tahu siswa')),
                ('kegiatan_pendahuluan', models.TextField(blank=True)),
                ('kegiatan_inti', models.TextField(blank=True)),
                ('kegiatan_penutup', models.TextField(blank=True)),
                ('asesmen', models.TextField(blank=True, help_text='Bentuk & teknik asesmen yang dipakai di pertemuan ini')),
                ('sumber_media', models.TextField(blank=True, help_text='Alat, media, dan sumber belajar yang dipakai')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modul_ajar', to='pjok.guruprofile')),
                ('materi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modul_ajar', to='pjok.materifase')),
                ('tp', models.ManyToManyField(blank=True, related_name='modul_ajar', to='pjok.tujuanpembelajaran')),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
